"""add cart popularity tracking

Revision ID: 3cb25bcfc1a0
Revises: 94404b2e4890
Create Date: 2025-09-24 17:07:02.727907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb25bcfc1a0'
down_revision: Union[str, Sequence[str], None] = '94404b2e4890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_popularity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_popularity_product_id'), 'cart_popularity', ['product_id'], unique=False)
    op.create_index(op.f('ix_cart_popularity_session_id'), 'cart_popularity', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_popularity_session_id'), table_name='cart_popularity')
    op.drop_index(op.f('ix_cart_popularity_product_id'), table_name='cart_popularity')
    op.drop_table('cart_popularity')
    # ### end Alembic commands ###
