"""add_featured_field_to_products

Revision ID: afa3d22d6ef1
Revises: 94404b2e4890
Create Date: 2025-09-22 19:22:41.777826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afa3d22d6ef1'
down_revision: Union[str, Sequence[str], None] = '94404b2e4890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('featured', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_products_featured'), 'products', ['featured'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_featured'), table_name='products')
    op.drop_column('products', 'featured')
    # ### end Alembic commands ###
