"""add_product_cart_counts_table

Revision ID: edf1d3831f5d
Revises: 94404b2e4890
Create Date: 2025-09-24 16:35:35.396303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf1d3831f5d'
down_revision: Union[str, Sequence[str], None] = '94404b2e4890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_cart_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_session', 'product_cart_counts', ['product_id', 'session_id'], unique=True)
    op.create_index(op.f('ix_product_cart_counts_product_id'), 'product_cart_counts', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_cart_counts_session_id'), 'product_cart_counts', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_cart_counts_session_id'), table_name='product_cart_counts')
    op.drop_index(op.f('ix_product_cart_counts_product_id'), table_name='product_cart_counts')
    op.drop_index('idx_product_session', table_name='product_cart_counts')
    op.drop_table('product_cart_counts')
    # ### end Alembic commands ###
