"""add featured and sales count to products

Revision ID: f976da1f5b43
Revises: 94404b2e4890
Create Date: 2025-10-03 15:11:53.870709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f976da1f5b43'
down_revision: Union[str, Sequence[str], None] = '94404b2e4890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_featured', sa.Boolean(), nullable=False, server_default=sa.text("0")))
    op.add_column('products', sa.Column('sales_count', sa.Integer(), nullable=False, server_default="0"))
    op.create_index(op.f('ix_products_is_featured'), 'products', ['is_featured'], unique=False)
    op.create_index(op.f('ix_products_sales_count'), 'products', ['sales_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_sales_count'), table_name='products')
    op.drop_index(op.f('ix_products_is_featured'), table_name='products')
    op.drop_column('products', 'sales_count')
    op.drop_column('products', 'is_featured')
    # ### end Alembic commands ###
